services:
    db:
        image: postgres:15.6-bullseye
        container_name: db
        restart: unless-stopped
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USERNAME:?err}
            POSTGRES_PASSWORD: ${DB_PASSWORD:?err}
            POSTGRES_DB: ${DB_DATABASE:?err}
        healthcheck:
            test: "pg_isready -U ${DB_USERNAME:?err} -d ${DB_DATABASE:?err}"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - app_network

    app:
        image: lara-pay
        container_name: lara-pay
        build: .
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - ./:/var/www
        env_file:
            - .env
        networks:
            - app_network

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: on-failure
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        ports:
            - 80:80
        networks:
            - app_network

    # supervisor:
    #     image: lara-pay
    #     networks:
    #         - app_network
    #     depends_on:
    #         - app
    #         - nginx
    #     command: supervisord

networks:
    app_network:
        driver: bridge
